class BoxRunner{
	public static void main(String values[]){
		String box0="violet";
		String box1="indigo";
		String box2="blue";
		String box3="green";
		String box4="yellow";
		String box5="orange";
		String box6="red";
		String box7="pink";
		String box8="purple";
		String box9="brown";
		String box10="white";
		String box11="black";
		String box12="cream";
		String box13="peach";
		String box14="rose";
		String box15="hot pink";
		String box16="baby pink";
		String box17="light blue";
		String box18="royal blue";
		String box19="sky blue";
		String box20="brick red";
		String box21="crimson";
		String box22="beige";
		String box23="off white";
		String box24="biscuit";
		String box25="teal";
		String box26="neon";
		String box27="maroon";
		String box28="lavender";
		String box29="pista green";
		
		String[] boxes={box0,box1,box2,box3,box4,box5,box6,box7,box8,box9,box10,box11,box12,box13,box14,box15,box16,box17,box18,box19,box20,box21,box22,box23,box24,box25,box26,box27,box28,box29};
		
		System.out.println(boxes[0]);
		System.out.println(boxes[1]);
		System.out.println(boxes[2]);
		System.out.println(boxes[3]);
		System.out.println(boxes[4]);
		System.out.println(boxes[5]);
		System.out.println(boxes[6]);
		System.out.println(boxes[7]);
		System.out.println(boxes[8]);
		System.out.println(boxes[9]);
		System.out.println(boxes[10]);
		System.out.println(boxes[11]);
		System.out.println(boxes[12]);
		System.out.println(boxes[13]);
		System.out.println(boxes[14]);
		System.out.println(boxes[15]);
		System.out.println(boxes[16]);
		System.out.println(boxes[17]);
		System.out.println(boxes[18]);
		System.out.println(boxes[19]);
		System.out.println(boxes[20]);
		System.out.println(boxes[21]);
		System.out.println(boxes[22]);
		System.out.println(boxes[23]);
		System.out.println(boxes[24]);
		System.out.println(boxes[25]);
		System.out.println(boxes[26]);
		System.out.println(boxes[27]);
		System.out.println(boxes[28]);
		System.out.println(boxes[29]);
		
		System.out.println("\n\n Updated colours \n\n");
		//update
		boxes[0]="cyan";
		boxes[1]="olive";
		boxes[2]="magenta";
		boxes[3]="tan";
		boxes[4]="teal";
		boxes[5]="turquoise green";
		boxes[6]="turquoise blue";
		boxes[7]="gray";
		boxes[8]="lime";
		boxes[9]="light green";
		boxes[10]="wheat";
		boxes[11]="golden";
		boxes[12]="silver";
		boxes[13]="dark blue";
		boxes[14]="navy blue";
		boxes[15]="aqua blue";
		boxes[16]="parrot green";
		boxes[17]="peacock green";
		boxes[18]="peacock blue";
		boxes[19]="bottle green";
		boxes[20]="salmon";
		boxes[21]="orchid";
		boxes[22]="apple green";
		boxes[23]="pearl white";
		boxes[24]="ivory";
		boxes[25]="emerald";
		boxes[26]="coral";
		boxes[27]="khaki";
		boxes[28]="copper";
		boxes[29]="bronze";
		
		System.out.println(boxes[0]);
		System.out.println(boxes[1]);
		System.out.println(boxes[2]);
		System.out.println(boxes[3]);
		System.out.println(boxes[4]);
		System.out.println(boxes[5]);
		System.out.println(boxes[6]);
		System.out.println(boxes[7]);
		System.out.println(boxes[8]);
		System.out.println(boxes[9]);
		System.out.println(boxes[10]);
		System.out.println(boxes[11]);
		System.out.println(boxes[12]);
		System.out.println(boxes[13]);
		System.out.println(boxes[14]);
		System.out.println(boxes[15]);
		System.out.println(boxes[16]);
		System.out.println(boxes[17]);
		System.out.println(boxes[18]);
		System.out.println(boxes[19]);
		System.out.println(boxes[20]);
		System.out.println(boxes[21]);
		System.out.println(boxes[22]);
		System.out.println(boxes[23]);
		System.out.println(boxes[24]);
		System.out.println(boxes[25]);
		System.out.println(boxes[26]);
		System.out.println(boxes[27]);
		System.out.println(boxes[28]);
		System.out.println(boxes[29]);
		
	}
}