class CountryRunner{
	public static void main(String[] args){
		Country.population("Afghanistan");
		Country.population("Albania");
		Country.population("Algeria");
		Country.population("Andorra");
		Country.population("Angola");
		Country.population("Antigua and Barbuda");
		Country.population("Argentina");			
		Country.population("Armenia");
		Country.population("Australia");
		Country.population("Austria");
		Country.population("Azerbaijan");
		Country.population("Bahamas");
		Country.population("Bahrain");
		Country.population("Bangladesh");
		Country.population("Barbados");
		Country.population("Belarus");
		Country.population("Belgium");
		Country.population("Belize");
		Country.population("Benin");
		Country.population("Bhutan");
		Country.population("Bolivia");
		Country.population("Bosnia and Herzegovina");
		Country.population("Botswana");
		Country.population("Brazil");
		Country.population("Brunei");
		Country.population("Bulgaria");
		Country.population("Burkina Faso");
		Country.population("Burundi");
		Country.population("Cabo Verde");
		Country.population("Cambodia");
		Country.population("Cameroon");
		Country.population("Canada");
		Country.population("Central African Republic");
		Country.population("Chad");
		Country.population("Chile");
		Country.population("China");
		Country.population("Colombia");
		Country.population("Comoros");
		Country.population("Congo, Democratic Rep.");
		Country.population("Congo, Republic of");
		Country.population("Costa Rica");
		Country.population("Croatia");
		Country.population("Cuba");
		Country.population("Cyprus");
		Country.population("Czech Republic");
		Country.population("Denmark");
		Country.population("Djibouti");
		Country.population("Dominica");
		Country.population("Dominican Republic");
		Country.population("East Timor");
		Country.population("Ecuador");
		Country.population("Egypt");
		Country.population("El Salvador");
		Country.population("Equatorial Guinea");
		Country.population("Eritrea");
		Country.population("Estonia");
		Country.population("Eswatini");
		Country.population("Ethiopia");
		Country.population("Fiji");
		Country.population("Finland");
		Country.population("France");
		Country.population("Gabon");
		Country.population("Gambia");
		Country.population("Georgia");
		Country.population("Germany");
		Country.population("Ghana");
		Country.population("Greece");
		Country.population("Grenada");
		Country.population("Guatemala");
		Country.population("Guinea");
		Country.population("Guinea-Bissau");
		Country.population("Guyana");
		Country.population("Haiti");
		Country.population("Honduras");
		Country.population("Hungary");
		Country.population("Iceland");
		Country.population("India");
		Country.population("Indonesia");
		Country.population("Iran");
		Country.population("Iraq");
		Country.population("Ireland");
		Country.population("Israel");
		Country.population("Italy");
		Country.population("Jamaica");
		Country.population("Japan");
		Country.population("Jordan");
		Country.population("Kazakhstan");
		Country.population("Kenya");
		Country.population("Kiribati");
		Country.population("Korea, North");
		Country.population("Korea, South");
		Country.population("Kosovo");
		Country.population("Kuwait");
		Country.population("Kyrgyzstan");
		Country.population("Laos");
		Country.population("Latvia");
		Country.population("Lebanon");
		Country.population("Lesotho");
		Country.population("Liberia");
		Country.population("Libya");
		Country.population("Liechtenstein");
		Country.population("Lithuania");
		Country.population("Luxembourg");
		Country.population("Madagascar");
		Country.population("Malawi");
		Country.population("Malaysia");
		Country.population("Maldives");
		Country.population("Mali");
		Country.population("Malta");
		Country.population("Marshall Islands");
		Country.population("Mauritania");
		Country.population("Mauritius");
		Country.population("Mexico");
		Country.population("Micronesia");
		Country.population("Moldova");
		Country.population("Monaco");
		Country.population("Mongolia");
		Country.population("Montenegro");
		Country.population("Morocco");
		Country.population("Mozambique");
		Country.population("Myanmar");
		Country.population("Namibia");
		Country.population("Nauru");
		Country.population("Nepal");
		Country.population("Netherlands");
		Country.population("New Zealand");
		Country.population("Nicaragua");
		Country.population("Niger");
		Country.population("Nigeria");
		Country.population("North Macedonia");
		Country.population("Norway");
		Country.population("Oman");
		Country.population("Pakistan");
		Country.population("Palau");
		Country.population("Panama");
		Country.population("Papua New Guinea");
		Country.population("Paraguay");
		Country.population("Peru");
		Country.population("Philippines");
		Country.population("Poland");
		Country.population("Portugal");
		Country.population("Qatar");
		Country.population("Romania");
		Country.population("Russia");
		Country.population("Rwanda");
		Country.population("Saint Kitts & Nevis");
		Country.population("Saint Lucia");
		Country.population("Saint Vincent & Grenadines");
		Country.population("Samoa");
		Country.population("San Marino");
		Country.population("Sao Tome & Principe");
		Country.population("Saudi Arabia");
		Country.population("Senegal");
		Country.population("Serbia");
		Country.population("Seychelles");
		Country.population("Sierra Leone");
		Country.population("Singapore");
		Country.population("Slovakia");
		Country.population("Slovenia");
		Country.population("Solomon Islands");
		Country.population("Somalia");
		Country.population("South Africa");
		Country.population("South Sudan");
		Country.population("Spain");
		Country.population("Sri Lanka");
		Country.population("Sudan");
		Country.population("Suriname");
		Country.population("Sweden");
		Country.population("Switzerland");
		Country.population("Syria");
		Country.population("Taiwan");
		Country.population("Tajikistan");
		Country.population("Tanzania");
		Country.population("Thailand");
		Country.population("Togo");
		Country.population("Tonga");
		Country.population("Trinidad & Tobago");
		Country.population("Tunisia");
		Country.population("Turkey");
		Country.population("Turkmenistan");
		Country.population("Tuvalu");
		Country.population("Uganda");
		Country.population("Ukraine");
		Country.population("United Arab Emirates");
		Country.population("United Kingdom");
		Country.population("United States");
		Country.population("Uruguay");
		Country.population("Uzbekistan");
		Country.population("Vanuatu");
		Country.population("Vatican City");
		Country.population("Venezuela");
		Country.population("Vietnam");
		Country.population("Yemen");
		Country.population("Zambia");
		Country.population("Zimbabwe");
		
		Country.population("Karnataka");
		
	}
}